# Generated by Django 3.0.3 on 2020-02-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_local_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='local_evento',
        ),
    ]
