# Generated by Django 3.0.3 on 2020-02-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_evento_local_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local do evento'),
        ),
    ]
