# Generated by Django 3.0.3 on 2020-03-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evento_local_evento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_cricao',
            new_name='data_create',
        ),
    ]
