# Generated by Django 3.0.3 on 2020-03-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200305_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cor',
            field=models.CharField(default='#3788d8', max_length=7),
        ),
    ]
